### ISSUE TITLE
[release] 4.0 tracker

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/choo#204]
## Major release, routing edition

Programmatic navigation is essential. But to achieve it we need to have breaking changes. And if we're going to break things, we might as well go all out again. So this issue is here to track the changes for the `4.0.0` release. All patches will be merged into [the 4 branch](https://github.com/yoshuawuyts/choo/tree/4), so that should provide an accurate representation of where things are at. Feedback and testing at any stage would be very welcome!
### Changes
- [x] slim down server side rendering API | [issue](https://github.com/yoshuawuyts/choo/issues/191) | [pull-request](https://github.com/yoshuawuyts/choo/pull/203)
- [x] update router API to be lisp-like | [issue]() | [pull-request]()
  - [x] update `sheet-router` to be lisp-like | [issue](https://github.com/yoshuawuyts/sheet-router/issues/29) | [pull-request](https://github.com/yoshuawuyts/sheet-router/pull/33)
  - [x] update `sheet-router` to add thunking | [issue](https://github.com/yoshuawuyts/sheet-router/issues/17) | [pull-request](https://github.com/yoshuawuyts/sheet-router/pull/34)
  - [x] update `wayfarer` to add a `walk` function | [issue](https://github.com/yoshuawuyts/wayfarer/issues/43) | [pull-request](https://github.com/yoshuawuyts/wayfarer/pull/45)
  - [x] update `sheet-router` to expose the `walk` function | [issue](https://github.com/yoshuawuyts/sheet-router/issues/30) | [pull-request](https://github.com/yoshuawuyts/sheet-router/pull/38)
  - [x] update `choo` to use the `walk` function | [pull-request](https://github.com/yoshuawuyts/choo/pull/206)
- [x] support inline anchor links | [issue](https://github.com/yoshuawuyts/choo/issues/65)
  - [ ] allow bypassing of link clicks in `sheet-router` | [issue](https://github.com/yoshuawuyts/sheet-router/issues/15) | [pull-request](https://github.com/yoshuawuyts/sheet-router/pull/27)
- [x] update router API to handle hashes by default
  - [x] update `sheet-router` to handle hashes by default | [issue](https://github.com/yoshuawuyts/sheet-router/issues/31)
- [x] update `location` state to expose `search` parameters (query strings) | [issue](https://github.com/yoshuawuyts/sheet-router/issues/31)
- [x] swap `state` and `data` argument order | [issue](https://github.com/yoshuawuyts/choo/issues/179)
- [ ] move opts from `app.start()` to `app = choo()`
- [ ] update documentation to reflect new changes
  - [ ] first pass
  - [ ] feedback round
- [ ] update examples to reflect new changes
  - [ ] first pass
  - [ ] feedback round
- [ ] update handbook to reflect new changes
  - [ ] first pass
  - [ ] feedback round
- [ ] create migration guide in handbook prefixed as `migration-` or `migrations/`
### See Also
- [4.0.0 branch](https://github.com/yoshuawuyts/choo/tree/4)
- [roadmap](https://github.com/yoshuawuyts/choo/issues/152)

**Comment by fczuardi** [comment]
migration note:

old: ```send('location:setLocation', { location: path }, done);```
new: ```send('location:set', { location: path }, done);```

**Comment by yoshuawuyts** [comment]
oh yeah, we've got a preliminary release branch up on `choo@4.0.0-0` - missing the arg order switch, but that's about it (:

**Comment by pyros2097** [comment]
If I'm starting a new project would it be better to use the 4.0.0 branch or the older one?
But need some documentation though to try it out.

**Comment by yoshuawuyts** [comment]
Either one should work; biggest blocker right now is docs tbh - there's a
PR in, and examples are like mostly up to date so you _could_ if you wanted
to

**Comment by yoshuawuyts** [comment]
`v4` was released - closing :grin:
