### ISSUE TITLE
3.0 release log

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/choo#42]
We're probably going to run some breaking changes, for the sake of a better API. These changes should get us around `5kb` optimized.

- [x] move `choo.view` out to `require('choo/html')` #71 | pr #103
- [x] streamline view API #35 | pr #111 
- [x] higher order functions #34 | pr #104
- [x] create lifecycle hooks #1 | feature addition in dependency covered by semver
- [x] implement state hooks #15 | pr #104 
- [x] add yo-yoify #3 | pr #110
- [x] rename "app" namespace #82 | pr #111 
- [x] enable browser testing | pr #86
- [x] propagating actions creates infinite loop #114 | pr #104 

When everything is merged:
- [x] validate all tests pass
- [x] validate all examples work
- [x] validate all docs are updated
- [x] write changelog

Please do comment if I've missed anything; I'm not a fan of breaking changes, but if it needs breaking this is the time to speak up. Cheers!

**Comment by toddself** [comment]
We should probably add 

[ ] enable browser testing

To this list :)

**Comment by yoshuawuyts** [comment]
@toddself feel free to update the release list as you like; I just happened to create it - anyone with commit rights should be able to do that ^__^
