### ISSUE TITLE
choo v5 release checklist

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/choo#429]
Choo `v5` is super close; this the stuff we need to do:

- [x] implement choo v5 API (#425)
- [x] update website
- [x] update handbook
- [x] probably just delete the rest of the handbook
- [x] update `choo-log` (branch ready)
- [x] update `choo-persist` (branch ready)
- [x] double check readme
- [ ] write patch notes
- [x] close like all issues

---

cc/ @bcomnes @timwis @toddself

**Comment by bcomnes** [comment]
I'll try to dip my toes in when I finish up a few other things.

**Comment by yoshuawuyts** [comment]
ok, added a warning to the handbook that it's out of date. Updated website, readme all the other stuff. Someone should write the patch notes (volunteers welcome!) but yeah hitting the release button right now

**Comment by yoshuawuyts** [comment]
ps we got mentioned in the [node newsletter](https://twitter.com/yoshuawuyts/status/844192889341132802) and oops they said v5 is out yet - so yeah given v5 is pretty much done we can def release. Here goeessss

**Comment by fyrkant** [comment]
Is there a upgrade guide from v4 -> v5 somewhere? Maybe someone updated a v4 app, leaving some nice juicy commit changes I could look through to get a hang of how things translate?

**Comment by yoshuawuyts** [comment]
@fyrkant uhhh, we should probably write patch notes but yeah like almost everything changed haha - I wrote down some of the changes [in an article](https://medium.com/@yoshuawuyts/choo-v5-bc775b007b5e#.yqnw19ap7) tho, I hope it makes sense

**Comment by tgfjt** [comment]
@yoshuawuyts I read the awesome article! but I felt "oh? where should I write `subscriptions[]`!?"
We would be happy with an upgrade guide or something example.:)

**Comment by tunnckoCore** [comment]
@tgfjt that's the tricky part, choo v5 seems to not be ELM-like anymore, everything is just events.

After looking it few days, i actually don't like v5.

More hints: 

- models are defined through `.use` method, "plugins" are passed with `state, emitter` signature, where `state` is empty object and `emitter` is real event emitter 
- the old `send` from the views is now `emitter.emit` function, which should be used to emit "actions" defined with `emitter.on` method from inside the "plugin" (which now is model)

**Comment by tunnckoCore** [comment]
@yoshuawuyts add "add tests" bullet to the list ;d

**Comment by tgfjt** [comment]
@tunnckoCore Is your concern that every models and any plugins can touch `state`?
Time to talk about v6 maybe?

**Comment by toddself** [comment]
@tunnckoCore I am unconvinced after building larger apps that an elm-style architecture is necessary and might actually cause much unneeded complexity and slowness. 

Javascript is not an immutable language and forcing it to be one is expensive in terms of memory and cpu cycles. 

Being rigorous about data and changes to it is great, but being forced into it feels very rigid imho. 

To each, however, their own.

**Comment by bcomnes** [comment]
People were talking about creating a choo5 adapter for https://github.com/yoshuawuyts/barracks

**Comment by tunnckoCore** [comment]
@tgfjt don't know, i didn't tried it yet, but it looks like that to me ;d

@toddself it's not needed state to be immutable to have elm architecture. Just separating the two styles of actions is enough and great. Cost nothing, for sure. Looks better & more clean, for sure. And it still can be event based :)

**Comment by YerkoPalma** [comment]
IMO choo v5 looks quite more interesting than v4. I've actually always avoided subscription, because they were almost are event listeners, and now that choo is all about event emitter is all more natural for me. I think I will rewrite some stuff now :)
