### ISSUE TITLE
timing API

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/choo#446]
In order to improve, we must measure first. Specifically when it comes to framerate there are very specific numbers we can rely on: `~16ms` for any given frame to achieve 60fps. So it'd be cool if for any given `emitter.emit('render')` call we'd know how long it took to complete.

In the browser there's the [window.Performance](https://developer.mozilla.org/en-US/docs/Web/API/Performance) API which was made specifically for these timings. In browsers where it's not supported there's [marky](https://github.com/nolanlawson/marky). We can add hooks to choo which allow reading from the performance API so we can detect if things are slow.

I already made a working demo, but it required patching a few things. I've outlined the steps below, and added a screenshot of the result. Thoughts and feedback would be v. welcome!

### tasks
- [x] add `performance.mark()` and `performance.measure()` hooks to `choo`
- [x] patch nanobus to run star emitters after normal emitters, so we can rely on `choo-log` to run after all `.on('render')` calls are done
- [x] add `performance.getEntries()` to `choo-log`

### screenshot
<img width="707" alt="screen shot 2017-03-28 at 16 44 01" src="https://cloud.githubusercontent.com/assets/2467194/24417851/4be12e04-13ea-11e7-9e2e-8ceeca714639.png">

**Comment by yoshuawuyts** [comment]
Cool, all PRs are out - reviews would be much appreciated!

**Comment by yoshuawuyts** [comment]
Latest screen 
<img width="707" alt="screen shot 2017-03-28 at 22 11 05" src="https://cloud.githubusercontent.com/assets/2467194/24425176/7d699862-1403-11e7-9545-f7103a7f4c1c.png">

**Comment by yoshuawuyts** [comment]
`v5.1.0` :sparkles:
